language: rust
cache: cargo
# According to travis docs, rust team appreciates if we test against all channels.
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt clippy
  - sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo build --no-default-features # build without webkit2gtk
  - cargo clippy -- -D warnings # run clippy
  - cargo clippy --no-default-features -- -D warnings # run clippy without webkit2gtk
  - cargo test
  - cargo test --no-default-features # test without webkit2gtk
